name: AntiVPN
main: me.egg82.antivpn.BungeeBootstrap
version: ${plugin.version}
author: egg82
api-version: 1.13
description: Get the best; save money on overpriced plugins and block VPN users!
softdepend: [Plan, PlaceholderAPI]